version: "3"

services:
  rule_engine_api:
    image: sqdhub/stamina-ews
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
